# Generated by Django 5.0.6 on 2024-07-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pista',
            name='tipo',
            field=models.CharField(choices=[('tenis', 'Tenis'), ('padel', 'Padel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
